apiVersion: v1
kind: Namespace
metadata:
  name: c2c-rafay-ns
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: c2c-rafay-deployment
  namespace: c2c-rafay-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: 792373136340.dkr.ecr.us-east-2.amazonaws.com/cisco_pov:c548c6463fd8af4ee986d99a82e0506369f34312

---
#Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: c2c-rafay-label
  name: c2c-rafay-service
  namespace: c2c-rafay-ns
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
  sessionAffinity: None
  type: LoadBalancer

---